stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
  - name: docker:dind
    command: ["--tls=false"]

  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_TLS_CERTDIR: ""
    
  before_script:
  - docker info
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main  
  tags:
    - henshin

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $VM_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $VM_USER@$VM_HOST "docker pull $IMAGE_TAG && docker stop my-portfolio || true && docker rm my-portfolio || true && docker run -d --name my-portfolio -p 80:80 $IMAGE_TAG
  only:
    - main  
  tags:
    - henshin  
